spring:
    profiles.active: __without-datajpa
    thymeleaf.cache: false
    datasource:
        url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username=sa
        password=
        driver-class-name=org.h2.Driver
    jpa.open-in-view: true
    dao.exceptiontranslation.enabled: false
server:
     port: 8090